import { db } from '../config/db';
import { signalPerformance, radarSignals } from '../models/market.model';
import { sql } from 'drizzle-orm';
import { deleteCache } from '../config/redis';

async function resetSignalPerformance(): Promise<void> {
    console.log('=== Reset Signal Performance ===\n');

    const count = await db.select({ total: sql<number>`count(*)::int` }).from(signalPerformance);
    const radarCount = await db.select({ total: sql<number>`count(*)::int` }).from(radarSignals);

    console.log(`signal_performance rows: ${count[0].total}`);
    console.log(`radar_signals rows:      ${radarCount[0].total}`);

    if (count[0].total === 0 && radarCount[0].total === 0) {
        console.log('\nNothing to delete. Tables are already empty.');
        return;
    }

    console.log('\nDeleting all signal_performance rows...');
    await db.delete(signalPerformance);
    console.log('  Done.');

    console.log('Deleting all radar_signals rows...');
    await db.delete(radarSignals);
    console.log('  Done.');

    try {
        await deleteCache('scorecard:latest');
        console.log('  Scorecard Redis cache cleared.');
    } catch {
        console.warn('  Could not clear Redis cache (may be unavailable).');
    }

    const afterCount = await db.select({ total: sql<number>`count(*)::int` }).from(signalPerformance);
    const afterRadar = await db.select({ total: sql<number>`count(*)::int` }).from(radarSignals);

    console.log('\n=== Result ===');
    console.log(`signal_performance: ${count[0].total} -> ${afterCount[0].total}`);
    console.log(`radar_signals:      ${radarCount[0].total} -> ${afterRadar[0].total}`);
    console.log('\nDone. New signals will be generated by the AI workflow with the updated model.');
}

resetSignalPerformance().catch((err) => {
    console.error('Reset failed:', err);
    process.exit(1);
});
