import type { Metadata } from 'next';
import Link from 'next/link';
import { SITE_URL } from '@/lib/constants';

export const metadata: Metadata = {
  title: 'Financial Disclaimer',
  description: 'OnlyAlpha Financial Disclaimer — important risk disclosures about AI-generated crypto intelligence.',
  openGraph: {
    title: 'Financial Disclaimer',
    description: 'OnlyAlpha Financial Disclaimer — important risk disclosures about AI-generated crypto intelligence.',
    url: `${SITE_URL}/disclaimer`,
    siteName: 'OnlyAlpha',
    type: 'website',
    images: [{ url: `${SITE_URL}/opengraph-image.png`, width: 1200, height: 630, alt: 'Financial Disclaimer — OnlyAlpha' }],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Financial Disclaimer',
    description: 'OnlyAlpha Financial Disclaimer — important risk disclosures about AI-generated crypto intelligence.',
  },
  alternates: {
    canonical: `${SITE_URL}/disclaimer`,
  },
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto py-8 px-4">
      <Link href="/" className="text-[#555] hover:text-[var(--color-primary)] text-sm font-mono block mb-6">
        ← Back to Home
      </Link>

      <h1 className="text-2xl font-bold text-white mb-2">Financial Disclaimer</h1>
      <p className="text-sm text-[#555] mb-8">Last Updated: April 2026</p>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">1. General Disclaimer</h2>
        <p className="text-sm text-[#888] leading-relaxed">
          OnlyAlpha provides AI-generated market intelligence, scenarios, analysis, and research related to cryptocurrencies and blockchain assets. All content on this platform is for <span className="text-white font-medium">informational and educational purposes only</span>. The information provided on this platform does not constitute, and should not be construed as, financial advice, investment advice, trading advice, or any other form of professional financial recommendation. By accessing and using this platform, you acknowledge and agree that you have read, understood, and accepted this disclaimer in its entirety.
        </p>
      </section>

      <section className="mb-8">
        <div className="bg-[#0A0A0A] border-l-4 border-[var(--color-primary)] p-4 rounded-r-lg mb-4">
          <h2 className="text-lg font-semibold text-white mb-3">2. Not Financial Advice</h2>
          <p className="text-sm text-[#888] leading-relaxed mb-3">
            <span className="text-red-500 font-bold">THIS IS THE MOST IMPORTANT SECTION.</span> Please read it carefully.
          </p>
          <ul className="list-disc list-inside text-sm text-[#888] space-y-2">
            <li>Content on OnlyAlpha <span className="text-white font-medium">does NOT constitute</span> investment advice, financial advice, trading advice, or solicitation to buy, sell, or hold any cryptocurrency or financial instrument</li>
            <li>OnlyAlpha is <span className="text-white font-medium">NOT a registered investment advisor</span>, broker-dealer, or financial planner</li>
            <li>OnlyAlpha is <span className="text-white font-medium">NOT licensed</span> to provide financial advice in any jurisdiction</li>
            <li>You should <span className="text-white font-medium">ALWAYS consult a licensed financial professional</span> before making any investment decision</li>
            <li>Cryptocurrency trading involves <span className="text-white font-medium">substantial risk of loss</span> and is not suitable for every investor</li>
            <li>Past performance shown on this platform <span className="text-white font-medium">does NOT guarantee</span> future results</li>
          </ul>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">3. AI-Generated Content</h2>
        <p className="text-sm text-[#888] leading-relaxed mb-3">
          All scenarios, market analysis, verdicts (Bullish/Bearish), confidence scores, airdrop recommendations, and research articles on OnlyAlpha are <span className="text-white font-medium">generated by artificial intelligence models</span>.
        </p>
        <ul className="list-disc list-inside text-sm text-[#888] space-y-2">
          <li>AI-generated content is <span className="text-white font-medium">NOT human recommendations</span></li>
          <li>AI models can and do produce <span className="text-white font-medium">errors, hallucinations, and inaccurate predictions</span></li>
          <li>There is <span className="text-white font-medium">NO guarantee</span> that AI-generated content is accurate, complete, reliable, or up-to-date</li>
          <li>AI systems may miss important market factors or fail to account for rapidly changing conditions</li>
          <li>You should <span className="text-white font-medium">NOT rely solely</span> on AI-generated content for making investment decisions</li>
          <li>OnlyAlpha is <span className="text-white font-medium">NOT responsible</span> for any losses resulting from reliance on AI-generated content</li>
        </ul>
      </section>

      <section className="mb-8">
        <div className="bg-[#0A0A0A] border-l-4 border-red-500 p-4 rounded-r-lg mb-4">
          <h2 className="text-lg font-semibold text-white mb-3">4. High-Risk Nature of Cryptocurrency</h2>
          <p className="text-sm text-[#888] leading-relaxed mb-3">
            <span className="text-red-500 font-bold">Cryptocurrency trading is EXTREMELY high-risk.</span>
          </p>
          <ul className="list-disc list-inside text-sm text-[#888] space-y-2">
            <li>Crypto markets are <span className="text-white font-medium">extremely volatile</span> — prices can swing 50%+ in hours or even minutes</li>
            <li>You can <span className="text-white font-medium">lose your entire investment</span> in a single trade</li>
            <li>Market manipulation, fraud, and scams are <span className="text-white font-medium">common</span> in the crypto space</li>
            <li>Exchanges can be hacked, go bankrupt, or freeze withdrawals</li>
            <li>Regulatory changes can <span className="text-white font-medium">dramatically impact</span> cryptocurrency values overnight</li>
            <li>Smart contracts can contain <span className="text-white font-medium">vulnerabilities or bugs</span> that result in loss of funds</li>
            <li>There is <span className="text-white font-medium">no insurance</span> for cryptocurrency losses (unlike FDIC insurance for bank deposits)</li>
          </ul>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">5. No Guarantee of Profits</h2>
        <p className="text-sm text-[#888] leading-relaxed mb-3">
          OnlyAlpha makes <span className="text-white font-medium">NO guarantee</span> of profits, returns, or accuracy.
        </p>
        <ul className="list-disc list-inside text-sm text-[#888] space-y-2">
          <li>Scenarios are <span className="text-white font-medium">directional opinions</span> based on data patterns, NOT predictions or guarantees</li>
          <li>There is <span className="text-white font-medium">NO assurance</span> that following scenarios will result in profits</li>
          <li>High confidence scores do <span className="text-white font-medium">NOT guarantee</span> positive outcomes</li>
          <li>Market conditions can change <span className="text-white font-medium">rapidly and unpredictably</span></li>
          <li>OnlyAlpha does <span className="text-white font-medium">NOT guarantee</span> the accuracy, timeliness, or completeness of any information</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">6. Do Your Own Research (DYOR)</h2>
        <p className="text-sm text-[#888] leading-relaxed mb-3">
          Users <span className="text-white font-medium">MUST conduct independent research</span> (DYOR) before making any investment decision.
        </p>
        <ul className="list-disc list-inside text-sm text-[#888] space-y-2">
          <li>Do <span className="text-white font-medium">NOT rely solely</span> on OnlyAlpha scenarios or analysis</li>
          <li>Verify information from <span className="text-white font-medium">multiple sources</span></li>
          <li>Understand the <span className="text-white font-medium">fundamentals and technology</span> behind any cryptocurrency</li>
          <li>Research the <span className="text-white font-medium">team, community, and development activity</span></li>
          <li>Consider your own <span className="text-white font-medium">financial situation, risk tolerance, and investment goals</span></li>
          <li>Start with <span className="text-white font-medium">small amounts</span> you can afford to lose</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">7. Market Scenario Disclaimer</h2>
        <p className="text-sm text-[#888] leading-relaxed mb-3">
          The Scorecard shows <span className="text-white font-medium">historical scenario performance</span> data.
        </p>
        <ul className="list-disc list-inside text-sm text-[#888] space-y-2">
          <li>Past scenario performance is <span className="text-white font-medium">historical data only</span></li>
          <li>Historical performance <span className="text-white font-medium">does NOT predict</span> future performance</li>
          <li>Historical outcome rates and returns shown are <span className="text-white font-medium">NOT indicative</span> of future results</li>
          <li>Market conditions that produced past results may <span className="text-white font-medium">not repeat</span></li>
          <li>The Scorecard is for <span className="text-white font-medium">transparency and educational purposes</span> only</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">8. Third-Party Data</h2>
        <p className="text-sm text-[#888] leading-relaxed mb-3">
          Market data and information are sourced from <span className="text-white font-medium">third-party APIs</span> (including but not limited to Binance, Moralis, and other data providers).
        </p>
        <ul className="list-disc list-inside text-sm text-[#888] space-y-2">
          <li>OnlyAlpha is <span className="text-white font-medium">NOT responsible</span> for data accuracy, delays, or errors from third-party sources</li>
          <li>Third-party data providers may experience <span className="text-white font-medium">outages, delays, or inaccuracies</span></li>
          <li>We rely on third-party data in <span className="text-white font-medium">good faith</span> but cannot guarantee its reliability</li>
          <li>Always <span className="text-white font-medium">verify critical data</span> from multiple sources before making decisions</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">9. No Fiduciary Duty</h2>
        <p className="text-sm text-[#888] leading-relaxed">
          OnlyAlpha <span className="text-white font-medium">owes no fiduciary duty</span> to any user. No client relationship is formed by using the platform. The relationship between OnlyAlpha and users is <span className="text-white font-medium">strictly informational</span>. OnlyAlpha does not act in your best interest, and you should not interpret any content on this platform as personalized advice tailored to your specific financial situation.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">10. Limitation of Liability</h2>
        <p className="text-sm text-[#888] leading-relaxed mb-3">
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ONLYALPHA, ITS TEAM, AND ITS AI SYSTEMS ARE NOT LIABLE FOR ANY FINANCIAL LOSSES, DAMAGES, OR DECISIONS MADE BASED ON PLATFORM CONTENT.
        </p>
        <ul className="list-disc list-inside text-sm text-[#888] space-y-2">
          <li>We are <span className="text-white font-medium">NOT liable</span> for trading losses, missed opportunities, or any other financial damages</li>
          <li>We are <span className="text-white font-medium">NOT liable</span> for inaccurate scenarios, analysis, or predictions</li>
          <li>We are <span className="text-white font-medium">NOT liable</span> for service downtime, data loss, or technical issues</li>
          <li>Your use of the platform is <span className="text-white font-medium">at your own risk</span></li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">11. Jurisdiction-Specific Warnings</h2>
        <p className="text-sm text-[#888] leading-relaxed mb-3">
          Cryptocurrency regulations <span className="text-white font-medium">vary significantly by country</span> and jurisdiction.
        </p>
        <ul className="list-disc list-inside text-sm text-[#888] space-y-2">
          <li>Users are <span className="text-white font-medium">solely responsible</span> for understanding and complying with their local laws</li>
          <li>Cryptocurrency trading may be <span className="text-white font-medium">illegal or restricted</span> in your jurisdiction</li>
          <li>Tax obligations on cryptocurrency gains <span className="text-white font-medium">vary by country</span></li>
          <li>Some jurisdictions have <span className="text-white font-medium">strict regulations</span> on crypto advertising, trading, or holding</li>
          <li>Consult with a <span className="text-white font-medium">local legal or tax professional</span> for jurisdiction-specific advice</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">12. Contact</h2>
        <p className="text-sm text-[#888] leading-relaxed">
          If you have any questions about this Financial Disclaimer or any concerns about the content on OnlyAlpha, please contact us at <a href="mailto:contact@onlyalphacrypto.com" className="text-[var(--color-primary)] hover:underline">contact@onlyalphacrypto.com</a>. We will respond to your inquiry within a reasonable timeframe.
        </p>
      </section>
    </div>
  );
}
