import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'OnlyAlpha Terms of Service — rules and guidelines for using our platform.',
};

export default function TermsOfService() {
  return (
    <div className="max-w-3xl mx-auto py-8 px-4">
      <Link href="/" className="text-[#555] hover:text-[var(--color-primary)] text-sm font-mono block mb-6">
        ← Back to Home
      </Link>

      <h1 className="text-2xl font-bold text-white mb-2">Terms of Service</h1>
      <p className="text-sm text-[#555] mb-8">Last Updated: April 2026</p>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
        <p className="text-sm text-[#888] leading-relaxed">
          By accessing or using the OnlyAlpha platform (&quot;Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you disagree with any part of these terms, then you may not access the Service. We reserve the right to modify these terms at any time. Your continued use of the Service following the posting of changes constitutes your acceptance of such changes.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
        <p className="text-sm text-[#888] leading-relaxed">
          OnlyAlpha is an AI-powered cryptocurrency intelligence platform that provides real-time market analysis, automated signal detection with confidence scoring, airdrop discovery and tracking, on-chain intelligence monitoring, and deep-dive research articles. All content, analysis, signals, and articles on the platform are generated by artificial intelligence models.
        </p>
      </section>

      <section className="mb-8">
        <div className="bg-[#0A0A0A] border-l-2 border-[var(--color-primary)] pl-4 py-3 pr-3 rounded-r-lg mb-4">
          <h3 className="text-base font-semibold text-white mb-2">⚠️ Not Financial Advice</h3>
          <p className="text-sm text-[#888] leading-relaxed">
            All content provided by OnlyAlpha is for informational and educational purposes only. It does NOT constitute financial advice, investment advice, trading advice, or any other form of professional financial recommendation. OnlyAlpha is NOT a registered investment advisor, broker-dealer, or financial planner. Always conduct your own research (DYOR) and consult a licensed financial professional before making any investment decisions. Cryptocurrency trading involves substantial risk of loss and is not suitable for every investor.
          </p>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">3. Not Financial Advice</h2>
        <p className="text-sm text-[#888] leading-relaxed mb-3">
          This is a critical section. Please read it carefully.
        </p>
        <ul className="list-disc list-inside text-sm text-[#888] space-y-1">
          <li>All content on OnlyAlpha is for informational purposes only</li>
          <li>Content does NOT constitute investment advice, financial advice, or trading advice</li>
          <li>OnlyAlpha is NOT a registered financial advisor, broker-dealer, or financial planner</li>
          <li>We are NOT soliciting you to buy, sell, or hold any cryptocurrency or financial instrument</li>
          <li>You should ALWAYS conduct your own independent research (DYOR) before making any investment decision</li>
          <li>Consult a licensed financial professional before making any investment decisions</li>
          <li>Past performance shown on the platform does NOT guarantee future results</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">4. User Conduct</h2>
        <p className="text-sm text-[#888] leading-relaxed mb-3">
          You agree NOT to use the Service for any unlawful purpose or in any way that could damage, disable, overburden, or impair the Service. Specifically, you agree NOT to:
        </p>
        <ul className="list-disc list-inside text-sm text-[#888] space-y-1">
          <li>Scrape, data mine, or otherwise collect data from the Service using automated means</li>
          <li>Reverse engineer, decompile, or disassemble any part of the Service</li>
          <li>Redistribute, republish, or resell any content from the Service</li>
          <li>Use the Service for any illegal activities or to facilitate illegal activities</li>
          <li>Interfere with or disrupt the Service or servers connected to the Service</li>
          <li>Attempt to gain unauthorized access to any portion of the Service</li>
          <li>Use the Service to transmit viruses, malware, or other malicious code</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">5. Intellectual Property</h2>
        <p className="text-sm text-[#888] leading-relaxed mb-3">
          All content, features, and functionality of the Service are owned by OnlyAlpha and are protected by international copyright, trademark, and other intellectual property laws.
        </p>
        <p className="text-sm text-[#888] leading-relaxed">
          You may NOT reproduce, modify, distribute, display, perform, publish, license, create derivative works from, offer for sale, or use any content from the Service without express written permission from OnlyAlpha. All AI-generated content, including but not limited to market analysis, signals, and articles, remains the intellectual property of OnlyAlpha.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">6. AI-Generated Content Disclaimer</h2>
        <p className="text-sm text-[#888] leading-relaxed mb-3">
          All signals, market analysis, verdicts (BUY/SELL), confidence scores, airdrop recommendations, and research articles on OnlyAlpha are generated by artificial intelligence models.
        </p>
        <ul className="list-disc list-inside text-sm text-[#888] space-y-1">
          <li>AI-generated content may contain errors, inaccuracies, or outdated information</li>
          <li>There is NO guarantee that AI-generated content is accurate, complete, or up-to-date</li>
          <li>AI models can and do produce hallucinations or false information</li>
          <li>You should NOT rely solely on AI-generated content for making investment decisions</li>
          <li>OnlyAlpha is NOT responsible for any losses resulting from reliance on AI-generated content</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">7. Limitation of Liability</h2>
        <p className="text-sm text-[#888] leading-relaxed mb-3">
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ONLYALPHA SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE.
        </p>
        <p className="text-sm text-[#888] leading-relaxed mb-3">
          IN NO EVENT SHALL ONLYALPHA&apos;S TOTAL LIABILITY TO YOU FOR ALL CLAIMS, DAMAGES, OR LOSSES ARISING OUT OF OR RELATING TO THE SERVICE EXCEED ONE HUNDRED DOLLARS ($100).
        </p>
        <p className="text-sm text-[#888] leading-relaxed">
          OnlyAlpha is NOT liable for: financial losses from cryptocurrency trading, decisions made based on inaccurate signals, service downtime, data loss, or any other damages arising from your use of the Service. Use the Service at your own risk.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">8. Third-Party Links</h2>
        <p className="text-sm text-[#888] leading-relaxed">
          The Service may contain links to third-party websites or resources. We provide these links only as a convenience and are not responsible for the content, products, or services on or available from those websites or resources. Links to third-party websites do not imply any endorsement by OnlyAlpha of such websites or the products, services, or opinions offered on such websites. Your use of third-party websites is at your own risk and subject to the terms and policies of those websites.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">9. Availability</h2>
        <p className="text-sm text-[#888] leading-relaxed mb-3">
          The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranty of any kind, express or implied. We do NOT guarantee that the Service will be:
        </p>
        <ul className="list-disc list-inside text-sm text-[#888] space-y-1">
          <li>Uninterrupted, timely, secure, or error-free</li>
          <li>Accurate, reliable, or free of viruses or other harmful components</li>
          <li>Able to meet your requirements or expectations</li>
        </ul>
        <p className="text-sm text-[#888] leading-relaxed mt-3">
          We reserve the right to modify, suspend, or discontinue the Service (or any part or content thereof) at any time with or without notice. We will not be liable to you or any third party for any modification, suspension, or discontinuation of the Service.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">10. Changes to Terms</h2>
        <p className="text-sm text-[#888] leading-relaxed">
          We reserve the right to modify these Terms at any time. All changes are effective immediately when we post them. Your continued use of the Service following the posting of revised Terms means that you accept and agree to the changes. You are expected to check this page frequently so you are aware of any changes, as they are binding on you. We will provide notice of material changes to these Terms by posting the updated Terms on the Service and updating the &quot;Last Updated&quot; date at the top of this page.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">11. Governing Law</h2>
        <p className="text-sm text-[#888] leading-relaxed">
          These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which OnlyAlpha operates, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that the remaining Terms will remain in full force and effect.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">12. Contact</h2>
        <p className="text-sm text-[#888] leading-relaxed">
          If you have any questions about these Terms of Service, please contact us at contact@onlyalphacrypto.com. We will respond to your inquiry within a reasonable timeframe.
        </p>
      </section>
    </div>
  );
}
