import type { Metadata } from 'next';
import { TerminalPageClient } from '@/features/terminal/components/TerminalPageClient';
import { terminalApi } from '@/features/terminal/api';
import { homeApi } from '@/features/home/api';

export const revalidate = 60;

const COINS = [
    'BTC', 'ETH', 'SOL', 'BNB', 'XRP', 'ADA', 'DOGE', 'AVAX',
    'DOT', 'MATIC', 'LINK', 'UNI', 'ATOM', 'NEAR', 'APT', 'ARB',
    'OP', 'SUI', 'SEI', 'TIA', 'JUP', 'WIF', 'PEPE', 'FLOKI',
    'INJ', 'FTM', 'RENDER', 'AAVE', 'MKR', 'SNX',
];

export function generateStaticParams() {
    return COINS.map((coin) => ({ coin: coin.toLowerCase() }));
}

const SITE_URL = 'https://onlyalphacrypto.com';

type Params = Promise<{ coin: string }>;

export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> {
    const { coin } = await params;
    const symbol = coin.toUpperCase();

    // Fetch the specific article generated by the AI to retrieve SEO tags
    let title = `${symbol} Terminal — Live Analysis & Intelligence`;
    let description = `Real-time AI-powered analysis, news, and intelligence for ${symbol}. Track price action, on-chain data, and market sentiment.`;
    let keywords: string[] | undefined = undefined;

    try {
        const { masterArticle } = await terminalApi.getMasterArticle(symbol);
        if (masterArticle) {
            if (masterArticle.metaTitle) title = masterArticle.metaTitle;
            if (masterArticle.metaDescription) description = masterArticle.metaDescription;
            if (masterArticle.seoKeywords && Array.isArray(masterArticle.seoKeywords)) {
                keywords = masterArticle.seoKeywords;
            }
        }
    } catch (e) {
        console.error('[SEO] Error fetching master article for metadata:', e);
    }

    // Since the AI prompt formats title as "Title | OnlyAlpha", use 'absolute' to avoid Next.js suffixing it again.
    return {
        title: {
            absolute: title,
        },
        description,
        keywords,
        openGraph: {
            title,
            description,
            url: `${SITE_URL}/terminal/${coin}`,
            type: 'website',
        },
        twitter: {
            card: 'summary_large_image',
            title,
            description,
        },
        alternates: {
            canonical: `${SITE_URL}/terminal/${coin}`,
        },
    };
}

export default async function CoinTerminalPage({
    params,
    searchParams
}: {
    params: Promise<{ coin: string }>;
    searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
    // 1. Fetch generic news
    const news = await terminalApi.getLatestWire();

    // 2. We can also fetch radar signals to inject them natively as the user requested in the video!
    const radarSignals = await homeApi.getRadarSignals();

    const resolvedParams = await params;
    const resolvedSearchParams = await searchParams;
    const coinSymbol = resolvedParams.coin.toUpperCase();

    const radarId = resolvedSearchParams.radarId ? Number(resolvedSearchParams.radarId) : undefined;
    const isAlphaFocus = resolvedSearchParams.alpha === 'true';

    // The component below natively handles merging and filtering now
    return <TerminalPageClient
        initialNews={news}
        coin={coinSymbol}
        radarSignals={radarSignals}
        initialRadarId={radarId}
        isAlphaFocus={isAlphaFocus}
    />;
}
