import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Contact Us',
  description: 'Get in touch with the OnlyAlpha team — questions, feedback, and partnership inquiries.',
};

export default function ContactPage() {
  return (
    <div className="max-w-3xl mx-auto py-8 px-4">
      <Link href="/" className="text-[#555] hover:text-[var(--color-primary)] text-sm font-mono block mb-6">
        ← Back to Home
      </Link>

      <h1 className="text-2xl font-bold text-white mb-2">Get in Touch</h1>
      <p className="text-sm text-[#555] mb-8">We&apos;d love to hear from you</p>

      <section className="mb-10">
        <div className="bg-[#0A0A0A] border border-[#222] rounded-lg p-6">
          <h2 className="text-base font-semibold text-[#AAA] mb-4">Contact Email</h2>
          <a
            href="mailto:contact@onlyalphacrypto.com"
            className="text-[var(--color-primary)] font-mono text-lg hover:underline block mb-2"
          >
            contact@onlyalphacrypto.com
          </a>
          <p className="text-xs text-[#555]">
            Click the email address to open your default email client
          </p>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-lg font-semibold text-white mb-4">What We Can Help With</h2>
        <div className="bg-[#0A0A0A] border border-[#222] rounded-lg p-6">
          <ul className="space-y-3">
            <li className="flex items-start gap-3">
              <span className="material-symbols-outlined text-[#555] text-base mt-0.5">help</span>
              <span className="text-sm text-[#888] leading-relaxed">
                General questions about the platform
              </span>
            </li>
            <li className="flex items-start gap-3">
              <span className="material-symbols-outlined text-[#555] text-base mt-0.5">bug_report</span>
              <span className="text-sm text-[#888] leading-relaxed">
                Bug reports or technical issues
              </span>
            </li>
            <li className="flex items-start gap-3">
              <span className="material-symbols-outlined text-[#555] text-base mt-0.5">handshake</span>
              <span className="text-sm text-[#888] leading-relaxed">
                Partnership and API inquiries
              </span>
            </li>
            <li className="flex items-start gap-3">
              <span className="material-symbols-outlined text-[#555] text-base mt-0.5">shield</span>
              <span className="text-sm text-[#888] leading-relaxed">
                Privacy and data requests
              </span>
            </li>
            <li className="flex items-start gap-3">
              <span className="material-symbols-outlined text-[#555] text-base mt-0.5">edit</span>
              <span className="text-sm text-[#888] leading-relaxed">
                Content corrections or feedback
              </span>
            </li>
          </ul>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-lg font-semibold text-white mb-3">Response Time</h2>
        <div className="bg-[#0A0A0A] border border-[#222] rounded-lg p-6">
          <p className="text-sm text-[#888] leading-relaxed">
            We aim to respond to all inquiries within <span className="text-white font-medium">48 hours</span> during business days (Monday–Friday). For urgent technical issues, please include &quot;URGENT&quot; in your email subject line.
          </p>
        </div>
      </section>

      <section className="mb-8">
        <div className="bg-[#111] border border-[#333] rounded-lg p-4">
          <div className="flex items-start gap-3">
            <span className="material-symbols-outlined text-[#555] text-base mt-0.5">info</span>
            <div>
              <h3 className="text-xs font-mono uppercase tracking-widest text-[#555] mb-2">Note</h3>
              <p className="text-xs text-[#555] leading-relaxed">
                OnlyAlpha is an AI-powered platform. For questions about specific market scenarios or market analysis, please note that all content is generated by AI and reviewed by our team. We cannot provide personalized investment advice or financial recommendations.
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
