import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'About OnlyAlpha',
  description: 'Learn about OnlyAlpha — AI-powered crypto intelligence for traders and investors.',
};

export default function AboutPage() {
  return (
    <div className="max-w-3xl mx-auto py-8 px-4">
      <Link href="/" className="text-[#555] hover:text-[var(--color-primary)] text-sm font-mono block mb-6">
        ← Back to Home
      </Link>

      <h1 className="text-2xl font-bold text-white mb-2">About OnlyAlpha</h1>

      <section className="mb-10">
        <div className="bg-gradient-to-r from-[#0A0A0A] to-[#111] border border-[#222] rounded-lg p-6">
          <h2 className="text-xl font-bold text-white mb-3">Our Mission</h2>
          <p className="text-base text-[#888] leading-relaxed">
            OnlyAlpha is an <span className="text-[var(--color-primary)] font-medium">AI-powered cryptocurrency intelligence platform</span> built for traders and investors who demand real-time, data-driven market insights. We leverage cutting-edge artificial intelligence to analyze thousands of data points, market signals, and on-chain metrics, delivering actionable intelligence that helps you make informed decisions in the fast-paced crypto market.
          </p>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-lg font-semibold text-white mb-4">What We Do</h2>
        <div className="bg-[#0A0A0A] border border-[#222] rounded-lg p-6">
          <ul className="space-y-3">
            <li className="flex items-start gap-3">
              <span className="material-symbols-outlined text-[var(--color-primary)] text-base mt-0.5">trending_up</span>
              <span className="text-sm text-[#888] leading-relaxed">
                <span className="text-white font-medium">Real-time AI Market Analysis</span> — Comprehensive analysis across 30+ cryptocurrencies with continuous monitoring
              </span>
            </li>
            <li className="flex items-start gap-3">
              <span className="material-symbols-outlined text-[var(--color-primary)] text-base mt-0.5">radar</span>
              <span className="text-sm text-[#888] leading-relaxed">
                <span className="text-white font-medium">Automated Signal Detection</span> — AI-powered signals with confidence scoring for informed decision-making
              </span>
            </li>
            <li className="flex items-start gap-3">
              <span className="material-symbols-outlined text-[var(--color-primary)] text-base mt-0.5">account_balance</span>
              <span className="text-sm text-[#888] leading-relaxed">
                <span className="text-white font-medium">On-Chain Intelligence</span> — Monitor whale activity, large transfers, and blockchain metrics in real-time
              </span>
            </li>
            <li className="flex items-start gap-3">
              <span className="material-symbols-outlined text-[var(--color-primary)] text-base mt-0.5">gift</span>
              <span className="text-sm text-[#888] leading-relaxed">
                <span className="text-white font-medium">Airdrop Discovery</span> — Discover and track upcoming airdrops with eligibility analysis
              </span>
            </li>
            <li className="flex items-start gap-3">
              <span className="material-symbols-outlined text-[var(--color-primary)] text-base mt-0.5">article</span>
              <span className="text-sm text-[#888] leading-relaxed">
                <span className="text-white font-medium">Deep-Dive Research</span> — Comprehensive research articles generated by multi-model AI systems
              </span>
            </li>
          </ul>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-lg font-semibold text-white mb-3">How It Works</h2>
        <p className="text-sm text-[#888] leading-relaxed mb-4">
          Our AI models analyze multiple data streams simultaneously to generate actionable intelligence:
        </p>
        <div className="bg-[#0A0A0A] border border-[#222] rounded-lg p-4 space-y-3">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-full bg-[#111] border border-[#222] flex items-center justify-center text-[var(--color-primary)] text-xs font-mono">1</div>
            <p className="text-sm text-[#888]">Real-time market data feeds from major exchanges</p>
          </div>
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-full bg-[#111] border border-[#222] flex items-center justify-center text-[var(--color-primary)] text-xs font-mono">2</div>
            <p className="text-sm text-[#888]">On-chain metrics and whale activity monitoring</p>
          </div>
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-full bg-[#111] border border-[#222] flex items-center justify-center text-[var(--color-primary)] text-xs font-mono">3</div>
            <p className="text-sm text-[#888]">News sentiment and social signal analysis</p>
          </div>
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-full bg-[#111] border border-[#222] flex items-center justify-center text-[var(--color-primary)] text-xs font-mono">4</div>
            <p className="text-sm text-[#888]">AI model processing with confidence scoring</p>
          </div>
        </div>
        <p className="text-sm text-[#888] leading-relaxed mt-4">
          The key advantage: <span className="text-[var(--color-primary)]">no human bias</span> in signal generation. Our AI systems analyze data objectively, based on patterns and metrics, not emotions or opinions.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-lg font-semibold text-white mb-3">Our Technology</h2>
        <p className="text-sm text-[#888] leading-relaxed mb-4">
          OnlyAlpha leverages state-of-the-art technology to deliver market intelligence:
        </p>
        <ul className="list-disc list-inside text-sm text-[#888] space-y-2">
          <li><span className="text-white font-medium">Multi-Model AI Routing:</span> Intelligent selection between DeepSeek, Gemini, GPT, and other leading AI models based on the task complexity and data type</li>
          <li><span className="text-white font-medium">Real-Time Data Integration:</span> Direct connections to major cryptocurrency exchanges for price, volume, and order book data</li>
          <li><span className="text-white font-medium">Blockchain Data Layer:</span> Integration with Moralis and other blockchain data providers for on-chain analytics</li>
          <li><span className="text-white font-medium">Confidence Scoring:</span> Every signal includes a confidence score based on data quality and model certainty</li>
          <li><span className="text-white font-medium">Performance Tracking:</span> Every signal is tracked and scorecarded, providing transparent historical performance data</li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="text-lg font-semibold text-white mb-3">Transparency</h2>
        <p className="text-sm text-[#888] leading-relaxed">
          We believe in complete transparency. Every signal generated by OnlyAlpha is <span className="text-[var(--color-primary)] font-medium">tracked, scorecarded, and visible</span> to all users. Our platform shows:
        </p>
        <ul className="list-disc list-inside text-sm text-[#888] space-y-1 mt-3">
          <li>Historical signal performance and win rates</li>
          <li>Confidence scores for each signal</li>
          <li>Timestamps and underlying data sources</li>
          <li>Clear identification of AI-generated content</li>
        </ul>
        <p className="text-sm text-[#888] leading-relaxed mt-4">
          No hidden calls. No secret algorithms. No &quot;black box&quot; trading systems. OnlyAlpha provides the tools and insights — you make the decisions.
        </p>
      </section>

      <section className="mb-10">
        <div className="bg-[#0A0A0A] border-l-4 border-red-500 pl-4 py-3 pr-3 rounded-r-lg">
          <h3 className="text-base font-semibold text-white mb-2">⚠️ Important Disclaimer</h3>
          <p className="text-sm text-[#888] leading-relaxed">
            OnlyAlpha is <span className="text-white font-medium">not a registered financial advisor</span>. All content, signals, and analysis are AI-generated and for <span className="text-white font-medium">informational purposes only</span>. Cryptocurrency trading involves substantial risk. Always do your own research (DYOR) and consult a licensed professional before making investment decisions.
          </p>
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">Contact Us</h2>
        <p className="text-sm text-[#888] leading-relaxed">
          Have questions about OnlyAlpha? Want to learn more about our technology? Reach out to us at <a href="mailto:contact@onlyalphacrypto.com" className="text-[var(--color-primary)] hover:underline">contact@onlyalphacrypto.com</a>. We&apos;d love to hear from you.
        </p>
      </section>
    </div>
  );
}
